---
- hosts: host3
  become: yes   
  tasks:
    - name: Install MySQL
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - docker.io
        - python-docker
        - python-mysqldb
        - mysql-server
    - name: Start the MySQL service
      service: 
        name: mysql 
        state: started
        enabled: true
    - name: update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "1212"
        login_user: root
        login_password: pass
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost    


